### ISSUE TITLE
Trying to use Manga Hasu source crash the app

### ISSUE THREAD

**Issue by Nagispace** [TheNetsky/community-extensions#52]
As stated in the title as soon as I try to read a chapter paperback instantly crash.
I can still add mangas to my library but trying to read a chapter will crash the app. Only happens with the manga hasu source and also happens with downloaded chapters.
Removing and reinstalling the source doesn't fix the issue, neither does the database repair.
Source was working fine a few days ago.
Exemple log extracted from the paperback log : 
```[INFO] [2024-06-20T23:55:39.578Z] [AsyncOperation:start():51] [AsyncOperation] RequestOperation - https://mangahasu.se/one-piece-oorLmZEBBEZZ-p10328.html
[INFO] [2024-06-20T23:55:40.337Z] [AsyncOperation:start():51] [AsyncOperation] RequestOperation - https://mangahasu.se/https://mangahasu.me/one-piece/chapter-1118-being-free-oorararaNEZZ-c2200466.html
[INFO] [2024-06-20T23:55:40.659Z] [ChapterRenderer:preloadPages(chapter:startFrom:):190] Preloading pages for chapter MangaHasu/https://mangahasu.me/one-piece/chapter-1118-being-free-oorararaNEZZ-c2200466.html
[INFO] [2024-06-20T23:55:40.661Z] [ChapterRenderer:preloadPages(chapter:startFrom:):184] IMAGE PREFETCH STATS:
[INFO] [2024-06-20T23:55:40.662Z] [ChapterRenderer:preloadPages(chapter:startFrom:):184]  SKIPPED []
[INFO] [2024-06-20T23:55:40.662Z] [ChapterRenderer:preloadPages(chapter:startFrom:):184]  FAILED: []
[INFO] [2024-06-20T23:55:40.663Z] [ChapterRenderer:preloadPages(chapter:startFrom:):184]  COMPLETED: []
[INFO] [2024-06-20T23:55:42.030Z] [AppDelegate:requestNotificationPermission():190] Notification permission granted
[INFO] [2024-06-20T23:55:42.177Z] [SceneDelegate:sceneDidBecomeActive(_:):36] Scene did become active
[INFO] [2024-06-20T23:55:42.189Z] [BetaAuthenticator:refreshAuthentication():108] Not authenticated
[INFO] [2024-06-20T23:55:42.191Z] [BetaAuthenticator:refreshAuthentication():108] Not authenticated```

**Comment by akuladrakon** [comment]
I'm having problems with Manga Hasu, as well, but it doesn't crash Paperback for me. When I go into a chapter, I get a black screen with 1/0 pages. 

Here's my log, as well:

[INFO] [2024-06-22T00:02:35.010Z] [ChapterRenderer:preloadPages(chapter:startFrom:):190] Preloading pages for chapter MangaHasu/https://mangahasu.me/corrupting-the-heroines-first-love-rozelle-scans/chapter-35-oorararaNEZZ-c2201203.html
[INFO] [2024-06-22T00:02:35.013Z] [ChapterRenderer:preloadPages(chapter:startFrom:):184] IMAGE PREFETCH STATS:
[INFO] [2024-06-22T00:02:35.015Z] [ChapterRenderer:preloadPages(chapter:startFrom:):184]  SKIPPED []
[INFO] [2024-06-22T00:02:35.016Z] [ChapterRenderer:preloadPages(chapter:startFrom:):184]  FAILED: []
[INFO] [2024-06-22T00:02:35.018Z] [ChapterRenderer:preloadPages(chapter:startFrom:):184]  COMPLETED: []

**Comment by TheNetsky** [comment]
Fixed

**Comment by Nagispace** [comment]
> Fixed

Paperback still crashes even after removing and reinstalling repo and source.
Are the changes pushed yet ?

**Comment by TheNetsky** [comment]
It works fine on my end

Are you loading an item from your library or loading one from the homepage?
